### ISSUE TITLE
Extension Status

### ISSUE THREAD

**Issue by conrad66** [bkbilly/Asterisk-Call-Status#1]
Good afternoon!
Is it possible to get Extension Status ?

**Comment by bkbilly** [comment]
The extensions are already displayed. 
Could you explain more what you need with an example?

**Comment by conrad66** [comment]
For example, I have an extension 111.
I would like to get its status and, after switching from the InUse state to the Idle state, perform an action in the home assistant.
The status of ensten is described here:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_ExtensionStatus

**Comment by bkbilly** [comment]
This is already being done, but in a more complicated way.
Everytime an extension status changes, it sends an MQTT event to the broker.
The inUse that you mention is the Up, or Ringing and the idle is when it doesn't exist. You can see an example of some events taken from my Asterisk server which are sent to MQTT broker. 
```
 idle
 XXXXXXXXXX->Grandma [voips.modulus.gr (Ring)]
 XXXXXXXXXX->Grandma [voips.modulus.gr (Ring), 541 (Ringing)]
 XXXXXXXXXX->Grandma [voips.modulus.gr (Up), 541 (Up)]
 idle
```

I am guessing that you may want to have a separate MQTT topic for each extension with it's status...

**Comment by conrad66** [comment]
Please forgive me for my google translator....
I want to get the status of the end of the conversation on a certain exten.
Perhaps separate MQTT topic for each extension with it's status will solve the problem.
But right now I can't get the idle status if another exten is busy.
If there is a conversation on another exten, I will not know that the conversation I need is over.

**Comment by bkbilly** [comment]
Thanks for sharing your implementation, it's very helpful!

I am going to close this issue because it's solved.
